name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Validate HTML exists at repo root
        run: |
          if [ ! -f "index.html" ]; then
            echo "Error: index.html not found at repo root"
            exit 1
          fi
          echo "HTML validation passed"
